version: '3'

services:
    postgres:
        image: postgres:9.6.2

    django:
        build: .
        depends_on:
            - postgres
        env_file: .env
        environment:
            DJANGO_SETTINGS_MODULE: 'mlb.settings'
