version: '3.2'

services:
    postgres:
        image: postgres:9.6.2

    django:
        image: mlb_django:latest
        build:
            context: .
            args:
                - RELEASE_AUTH
        depends_on:
            - postgres
        environment:
            DJANGO_SETTINGS_MODULE: 'mlb.settings'
        command: runserver
        secrets:
            - SECRET_KEY
            - DATABASE_URL
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

secrets:
    SECRET_KEY:
        file: ./secrets/secret_key
    DATABASE_URL:
        file: ./secrets/database_url
    AWS_ACCESS_KEY_ID:
        file: ./secrets/aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
        file: ./secrets/aws_secret_access_key
    POSTGRES_PASSWORD:
        file: ./secrets/postgres_password
