version: '3.2'
services:
    postgres:
        image: postgres:9.6.3-alpine

    django:
        volumes:
            - '.:/app'
        ports:
            - 8000:8000
        environment:
            DEBUG: 'True'
            DJANGO_ALLOWED_HOSTS: 'localhost'
            RECALL_DISABLE: 'True'
            SECRET_KEY: 'thyzNahan'
            DATABASE_URL: 'psql://postgres:postgres@postgres:5432/postgres'
            CELERY_TASK_ALWAYS_EAGER: 'True'
    celery:
        volumes:
            - '.:/app'
        environment:
            DEBUG: 'True'
            RECALL_DISABLE: 'True'
            SECRET_KEY: 'thyzNahan'
            DATABASE_URL: 'psql://postgres:postgres@postgres:5432/postgres'
