version: '3'
services:
    django:
        ports:
            - 8000:8000
        environment:
            DEBUG: 'False'
            GUNICORN_CMD_ARGS: '--bind=0.0.0.0:8000 --workers=2'
        command: gunicorn
