version: '3.2'
services:
    nginx:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        restart: always
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
    postgres:
        restart: always
        deploy:
            placement:
                constraints:
                    - node.role == manager
    postgres-backup:
        image: localhost:5000/postgres-backup-s3:latest
        build:
            context: ./postgres_backup
        depends_on:
            - postgres
        environment:
            SCHEDULE: "@daily"
            S3_BUCKET: mlb-backups
            S3_PREFIX: 'postgresql'
            POSTGRES_DATABASE: postgres
            POSTGRES_USER: postgres
            POSTGRES_HOST: postgres
        secrets:
            - POSTGRES_PASSWORD
            - S3_SECRET_ACCESS_KEY
            - S3_ACCESS_KEY_ID

    django:
        image: localhost:5000/mlb_django:latest
        environment:
            DEBUG: 'False'
            GUNICORN_CMD_ARGS: '--bind=0.0.0.0:8000 --workers=2'
            VIRTUAL_HOST: mlb-queue.imagination.net
            DJANGO_ALLOWED_HOSTS: mlb-queue.imagination.net
            CORS_ORIGIN_ALLOW_ALL: 'True'
        depends_on:
            - postgres
            - nginx
        command: gunicorn
        restart: always
        deploy:
            mode: global
        secrets:
            - SLACK_TOKEN

secrets:
    SECRET_KEY:
        external: true
    DATABASE_URL:
        external: true
    POSTGRES_PASSWORD:
        external: true
    AWS_ACCESS_KEY_ID:
        external: true
    AWS_SECRET_ACCESS_KEY:
        external: true
    S3_ACCESS_KEY_ID:
        external: true
    S3_SECRET_ACCESS_KEY:
        external: true
    SLACK_TOKEN:
        external: true
