version: '3.2'
services:
    django:
        volumes:
            - '.:/app'
        ports:
            - 8000:8000
        environment:
            DEBUG: 'True'
            DJANGO_ALLOWED_HOSTS: 'localhost'
            RECALL_DISABLE: 'True'
            SECRET_KEY: 'thyzNahan'
            DATABASE_URL: 'psql://postgres:postgres@postgres:5432/postgres'
            CELERY_TASK_ALWAYS_EAGER: 'True'
            CELERY_BROKER_URL: 'redis://redis:6379/0'
        depends_on:
            - redis
    celery:
        volumes:
            - '.:/app'
        environment:
            DEBUG: 'True'
            RECALL_DISABLE: 'True'
            SECRET_KEY: 'thyzNahan'
            DATABASE_URL: 'psql://postgres:postgres@postgres:5432/postgres'
            CELERY_BROKER_URL: 'redis://redis:6379/0'
        depends_on:
            - redis
    redis:
        image: redis:3.0-alpine

