version: '3.2'

services:
    postgres:
        image: postgres:9.6.2

    django:
        image: mlb_django:latest
        build:
            context: .
            args:
                - RELEASE_AUTH
        depends_on:
            - postgres
        environment:
            DJANGO_SETTINGS_MODULE: 'mlb.settings'
        command: runserver
