version: '3.2'
services:

    nginx:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "./nginx.conf:/etc/nginx/vhost.d/mlb.sse.xp.imagination.net:ro"
            - "media:/app/media"

    redis:
        restart: always

    postgres:
        restart: always
        env_file: /var/secrets/env
        ports:
            - "5432:5432"
        volumes:
            - "pgdata:/var/lib/postgresql/data"
        environment:
            PGDATA: '/var/lib/postgresql/data/pgdata'

    django:
        environment:
            DEBUG: 'False'
            GUNICORN_CMD_ARGS: '--bind=0.0.0.0:8000 --workers=2'
            VIRTUAL_HOST: mlb.sse.xp.imagination.net
            DJANGO_ALLOWED_HOSTS: "*"
            CORS_ORIGIN_ALLOW_ALL: 'True'
            DJANGO_HOST: mlb.sse.xp.imagination.net
            LIGHTING_DISABLE: 'True'
        ports:
            - "8000:8000"
        volumes:
            - "media:/app/media"
        depends_on:
            - nginx
        command: gunicorn
        restart: always
        env_file: /var/secrets/env

    celery:
        environment:
            DEBUG: 'False'
            DJANGO_HOST: mlb.sse.xp.imagination.net
        volumes:
            - "media:/app/media"
        restart: always
        env_file: /var/secrets/env

volumes:
    pgdata:
    media:
