version: '3.2'
services:
    django:
        volumes:
            - '.:/app'
        ports:
            - 8000:8000
        environment:
            DEBUG: 'True'
            DJANGO_ALLOWED_HOSTS: 'localhost'
            RECALL_DISABLE: 'True'
