version: '3'
services:
    nginx:
        image: jwilder/nginx-proxy
        ports:
            - 80:80
        restart: always
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
    postgres:
        restart: always
    postgres-backup:
        image: schickling/postgres-backup-s3
        env_file: .env
        depends_on:
            - postgres
        environment:
            SCHEDULE: "@daily"
            S3_BUCKET: mlb-backups
            S3_PREFIX: 'postgresql'
            POSTGRES_DATABASE: postgres
            POSTGRES_USER: postgres
            POSTGRES_HOST: postgres

    django:
        environment:
            DEBUG: 'False'
            GUNICORN_CMD_ARGS: '--bind=0.0.0.0:8000 --workers=2'
            VIRTUAL_HOST: ec2-34-253-189-189.eu-west-1.compute.amazonaws.com
            DJANGO_ALLOWED_HOSTS: ec2-34-253-189-189.eu-west-1.compute.amazonaws.com
        depends_on:
            - postgres
            - nginx
        command: gunicorn
        restart: always
