version: '3.2'

services:

    postgres:
        image: postgres:9.6.3-alpine

    chrome:
        image: justinribeiro/chrome-headless
        command: [ "--headless",
                   "--disable-gpu",
                   "--remote-debugging-address=0.0.0.0",
                   "--remote-debugging-port=9222",
                   "--window-size=1080,1080"]
        cap_add:
            - SYS_ADMIN

    django:
        image: mlb_django:latest
        build: .
        depends_on:
            - postgres
        environment:
            DJANGO_SETTINGS_MODULE: 'mlb.settings'
        command: runserver

    celery:
        image: mlb_django:latest
        build: .
        depends_on:
            - postgres
            - chrome
        command: celery

