version: '3.2'
services:

    postgres:
        environment:
            REPLICATE_FROM: '192.168.254.100'

    jenkins:
        image: shimmi/jenkins:latest
        restart: always
        user: root
        volumes:
            - jenkins-home:/var/jenkins_home
            - /var/secrets/env:/var/secrets/env
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            VIRTUAL_HOST: mlb-jenkins.imagination.net
            VIRTUAL_PORT: "8080"

