version: '3.2'

services:

    postgres:
        image: postgres:9.6.3-alpine

    redis:
        image: redis:3.0-alpine

    django:
        image: mlb_django:latest
        build: .
        depends_on:
            - postgres
            - redis
        environment:
            DJANGO_SETTINGS_MODULE: 'mlb.settings'
        command: runserver

    celery:
        image: mlb_django:latest
        build: .
        depends_on:
            - postgres
            - redis
        command: celery

