version: '3.2'
services:

    nginx:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        restart: always
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"

    postgres:
        restart: always
        volumes:
            - "pgdata:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD_FILE: '/run/secrets/POSTGRES_PASSWORD'
        secrets:
            - POSTGRES_PASSWORD

    postgres-backup:
        build:
            context: ./postgres_backup
        depends_on:
            - postgres
        environment:
            SCHEDULE: "@daily"
            S3_BUCKET: mlb-backups
            S3_PREFIX: 'postgresql-nuc'
            POSTGRES_DATABASE: postgres
            POSTGRES_USER: postgres
            POSTGRES_HOST: postgres
        secrets:
            - POSTGRES_PASSWORD
            - S3_SECRET_ACCESS_KEY
            - S3_ACCESS_KEY_ID

    django:
        environment:
            DEBUG: 'False'
            GUNICORN_CMD_ARGS: '--bind=0.0.0.0:8000 --workers=2'
            VIRTUAL_HOST: mlb-queue.imagination.net
            DJANGO_ALLOWED_HOSTS: "*"
            CORS_ORIGIN_ALLOW_ALL: 'True'
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        ports:
            - "8000:8000"
        depends_on:
            - postgres
            - nginx
        command: gunicorn
        restart: always
        secrets:
            - SECRET_KEY
            - DATABASE_URL
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - SLACK_TOKEN

    celery:
        environment:
            DEBUG: 'False'
        restart: always
        secrets:
            - SECRET_KEY
            - DATABASE_URL
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - SLACK_TOKEN

volumes:
    pgdata:

secrets:
    SECRET_KEY:
        file: ./secrets/secret_key
    DATABASE_URL:
        file: ./secrets/database_url
    AWS_ACCESS_KEY_ID:
        file: ./secrets/aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
        file: ./secrets/aws_secret_access_key
    POSTGRES_PASSWORD:
        file: ./secrets/postgres_password
    S3_ACCESS_KEY_ID:
        file: ./secrets/aws_access_key_id
    S3_SECRET_ACCESS_KEY:
        file: ./secrets/aws_secret_access_key
    SLACK_TOKEN:
        file: ./secrets/slack_token
