# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170522_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='handedness',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='R', max_length=1, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='signed_waiver',
            field=models.BooleanField(default=False),
        ),
    ]
