# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 13:03
from __future__ import unicode_literals
from datetime import date

from django.db import migrations


def forwards(apps, schema_editor):
    Show = apps.get_model('game', 'Show')
    Game = apps.get_model('game', 'Game')
    welcome_message = ("Welcome to #mlbbattlegrounds. We’ll text you when it’s your "
                       "turn to bat. Enjoy Boston or L.A. food while you wait. Prepare "
                       "for beastmode!")
    recall_message = ("Ready to smash it? Because it’s your turn to bat now! "
                      "Please head over to the batting cage where we’re waiting for "
                      "you. Do your team proud!")
    souvenir_message = ("Thanks for playing! Download your pic here: {} "
                        "If you like this, you’ll love our event on July 4th: "
                        "http://bit.ly/mlbbg")
    show = Show.objects.create(welcome_message=welcome_message,
                               recall_message=recall_message,
                               souvenir_message=souvenir_message,
                               date=date(2017,6,30))
    Game.objects.update(show=show)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170930_1302'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
