# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 09:48
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20170930_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
