# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 13:14
from __future__ import unicode_literals

from django.db import migrations


def create_users(apps, schema_editor):
    User = apps.get_model('game', 'User')
    if not User.objects.filter(username='user').count():
        user = User.objects.create(
                username='user',
                password='pbkdf2_sha256$36000$OGYjuR6bFazH$mlmIPMIQlhnGrQ6KCLbXHUBOFS1MIVTNv6YiWwlmHpg=',
                is_staff=True,
                is_superuser=True)
    if not User.objects.filter(username='mlbvrgame').count():
        user = User.objects.create(
                username='mlbvrgame',
                password='pbkdf2_sha256$36000$BTfJRJlVCGAT$a0vC1doxbZOcPHrYwDnenB6uUuwe+ZHtOTWe8kVoREE=',
                is_staff=True)
    if not User.objects.filter(username='mlbtablet').count():
        user = User.objects.create(
                username='mlbtablet',
                password='pbkdf2_sha256$36000$NHje43lxf5Yo$+Fw0Tv8TVLiC6tpLgmtQmhb0ljmlA2a4oyyuRdF5g/g=',
                is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20180618_1314'),
    ]

    operations = [
        migrations.RunPython(create_users, migrations.RunPython.noop),
    ]
